dicinario_palavras = {
    'A': {
        'Carro':                                                         'amarok',
        'Sobremesa':                                                     'acai',
        'Sobrenome':                                                     'amaro',
        'Musica':                                                        'all stars',
        'Celebridade':                                                   'ayrton senna',
        'Instrumento musical':                                           'arpa',
        'App ou site':                                                   'aol com',
        'Game':                                                          'ark',
        'Eletro eletronico':                                             'airpod',
        'Verbo':                                                         'aspirar',
        'Marca':                                                         'audi',
        'Cidade':                                                        'adamantina',
        'Vestuario':                                                     'agasalho',
        'Serie':                                                         'away',
        'Animal':                                                        'anta',
        'Time esportivo':                                                'anapolis',
        'Cep':                                                           'amsterdam',
        'Remedio':                                                       'anador',
        'Pch':                                                           'antebraco',
        'Adjetivo':                                                      'amado',
        'Programa de tv':                                                'a fazenda',
        'Liquido':                                                       'agua',
        'Comida':                                                        'aspargos',
        'Esporte':                                                       'altetismp',
        'Cor':                                                           'azul',
        'Inseto':                                                        'abelha',
        'Nome feminino':                                                 'amanda',
        'Profissao':                                                     'artista',
        'Ator':                                                          'antonio fagundes',
        'Doce':                                                          'alfajor',
        'Idioma':                                                        'arquiro verde',
        'Flor':                                                          'azaleia',
        'Palavra em ingles':                                             'ant',
        'Jlr':                                                           'asno',
        'Gentilico':                                                     'afegao',
        'Personagem ficticio':                                           'alemao',
        'Filme':                                                         'as branquelas',
        'Mse':                                                           'anta',
        'Desenho animado':                                               'alvin e os ',
        'Fruta':                                                         'Amora',
        'Nome masculino':                                                'arthur',
        'Capital':                                                       'amisterda',
        'Cantor':                                                        'adelle',
        'Esportista':                                                    'ayrton senna',
        'Super heroi':                                                   'arqueiro verde',
        'Pda':                                                           'asas',
        'Objeto':                                                        'agulha',
        'Banda':                                                         'ac dc',
        'Meio de transporte':                                            'aviao'
    },
    'B': {
        'Carro':                                                         'boxer',
        'Sobremesa':                                                     'berimbau',
        'Sobrenome':                                                     'blink',
        'Musica':                                                        'basecamp',
        'Celebridade':                                                   'beon c',
        'Instrumento musical':                                           'beber',
        'App ou site':                                                   'bmw',
        'Game':                                                          'brumadinho',
        'Eletro eletronico':                                             'blusa',
        'Verbo':                                                         'beijar',
        'Marca':                                                         'besta',
        'Cidade':                                                        'berlim',
        'Vestuario':                                                     'blusa',
        'Serie':                                                         'breaking bad',
        'Animal':                                                        'baço',
        'Time esportivo':                                                'bonito',
        'Cep':                                                           'brasil',
        'Remedio':                                                       'baby med',
        'Pch':                                                           'bacon',
        'Adjetivo':                                                      'basquete',
        'Programa de tv':                                                'branco',
        'Liquido':                                                       'besouro',
        'Comida':                                                        'beatriz',
        'Esporte':                                                       'bancario',
        'Cor':                                                           'bruno Gagliaço',
        'Inseto':                                                        'barata',
        'Nome feminino':                                                 'bruna',
        'Profissao':                                                     'bromelia ',
        'Ator':                                                          'bruno gagliasso',
        'Doce':                                                          'bananinha',
        'Idioma':                                                        'basco',
        'Flor':                                                          'bromelia',
        'Palavra em ingles':                                             'ball',
        'Jlr':                                                           'bonito',
        'Gentilico':                                                     'bruno',
        'Personagem ficticio':                                           'barry allen',
        'Filme':                                                         'bruno',
        'Mse':                                                           'burra',
        'Desenho animado':                                               'benito de paula',
        'Fruta':                                                         'banana',
        'Nome masculino':                                                'bruno',
        'Capital':                                                       'berlin',
        'Cantor':                                                        'bruno mars',
        'Esportista':                                                    'bernanrdo silva',
        'Super heroi':                                                   'barry allen',
        'Pda':                                                           'baixo',
        'Objeto':                                                        'bola',
        'Banda':                                                         'byob',
        'Meio de transporte':                                            'barco'
    },
    'C': {
        'Carro':                                                         'camaro',
        'Sobremesa':                                                     'chocolate',
        'Sobrenome':                                                     'carvalho',
        'Musica':                                                        'come as you are',
        'Celebridade':                                                   'cardi b',
        'Instrumento musical':                                           'catuaba',
        'App ou site':                                                   'cvc',
        'Game':                                                          'call of duty',
        'Eletro eletronico':                                             'celular',
        'Verbo':                                                         'correr',
        'Marca':                                                         'crown',
        'Cidade':                                                        'cacequi.',
        'Vestuario':                                                     'camisa',
        'Serie':                                                         'californicatiom',
        'Animal':                                                        'crocodilo',
        'Time esportivo':                                                'corinthans',
        'Cep':                                                           'croacia',
        'Remedio':                                                       'corticoide',
        'Pch':                                                           'cabeça ',
        'Adjetivo':                                                      'carinhoso',
        'Programa de tv':                                                'caldeirao do hulk',
        'Liquido':                                                       'coca cola',
        'Comida':                                                        'camarão',
        'Esporte':                                                       'canoagem',
        'Cor':                                                           'cinza escuro',
        'Inseto':                                                        'cabo verde',
        'Nome feminino':                                                 'camila',
        'Profissao':                                                     'cientista',
        'Ator':                                                          'caio castro',
        'Doce':                                                          'castanha de caju',
        'Idioma':                                                        'croata',
        'Flor':                                                          'cravo',
        'Palavra em ingles':                                             'crown',
        'Jlr':                                                           'cole',
        'Gentilico':                                                     'calmo',
        'Personagem ficticio':                                           'cebolinha',
        'Filme':                                                         'cabo do medo',
        'Mse':                                                           'coitada',
        'Desenho animado':                                               'capitao caverna',
        'Fruta':                                                         'caqui',
        'Nome masculino':                                                'caio',
        'Capital':                                                       'caracas',
        'Cantor':                                                        'chico silva',
        'Esportista':                                                    'cristiano ronaldo',
        'Super heroi':                                                   'capitao america',
        'Pda':                                                           'caso',
        'Objeto':                                                        'cortina',
        'Banda':                                                         'coldplay',
        'Meio de transporte':                                            'carro'
    },
    'D': {
        'Carro':                                                         'discovery',
        'Sobremesa':                                                     'danoninho',
        'Sobrenome':                                                     'diniz',
        'Musica':                                                        'deicda',
        'Celebridade':                                                   'drake',
        'Instrumento musical':                                           'daxofone',
        'App ou site':                                                   'dicionario online',
        'Game':                                                          'dreams',
        'Eletro eletronico':                                             'digitalizador',
        'Verbo':                                                         'dormir',
        'Marca':                                                         'dannete',
        'Cidade':                                                        'dallas',
        'Vestuario':                                                     'dedal',
        'Serie':                                                         'dance academy',
        'Animal':                                                        'dromedario',
        'Time esportivo':                                                'dinamarca',
        'Cep':                                                           'dinamarca',
        'Remedio':                                                       'doril',
        'Pch':                                                           'dedos',
        'Adjetivo':                                                      'doida',
        'Programa de tv':                                                'dance o clip',
        'Liquido':                                                       'doce de leite',
        'Comida':                                                        'damasco',
        'Esporte':                                                       'danca',
        'Cor':                                                           'dorado',
        'Inseto':                                                        'dupin',
        'Nome feminino':                                                 'denise',
        'Profissao':                                                     'dentista',
        'Ator':                                                          'daniele suzuki',
        'Doce':                                                          'damasco',
        'Idioma':                                                        'dinamarques',
        'Flor':                                                          'dalia',
        'Palavra em ingles':                                             'dude',
        'Jlr':                                                           'dente',
        'Gentilico':                                                     'dunto',
        'Personagem ficticio':                                           'dumbo',
        'Filme':                                                         'd tox',
        'Mse':                                                           'doida',
        'Desenho animado':                                               'dragon ball',
        'Fruta':                                                         'damasco',
        'Nome masculino':                                                'diogo',
        'Capital':                                                       'dublim',
        'Cantor':                                                        'david brownie',
        'Esportista':                                                    'david villa',
        'Super heroi':                                                   'demolidor',
        'Pda':                                                           'dedo',
        'Objeto':                                                        'dedal',
        'Banda':                                                         'drake',
        'Meio de transporte':                                            'dirigvel'
    },
    'E': {
        'Carro':                                                         'elba',
        'Sobremesa':                                                     'enroladinho doce',
        'Sobrenome':                                                     'estevis',
        'Musica':                                                        'entrevista',
        'Celebridade':                                                   'eric gill',
        'Instrumento musical':                                           'eufonio',
        'App ou site':                                                   'enciclopedia online',
        'Game':                                                          'efootball',
        'Eletro eletronico':                                             'estabilizador',
        'Verbo':                                                         'esperar',
        'Marca':                                                         'ebay',
        'Cidade':                                                        'eldorado',
        'Vestuario':                                                     'espartihlo',
        'Serie':                                                         'emily em paris',
        'Animal':                                                        'elefante',
        'Time esportivo':                                                'egito',
        'Cep':                                                           'egito',
        'Remedio':                                                       'ebastel',
        'Pch':                                                           'estomago',
        'Adjetivo':                                                      'esbelto',
        'Programa de tv':                                                'eliana',
        'Liquido':                                                       'esfoliador facial',
        'Comida':                                                        'damasco',
        'Esporte':                                                       'esgrima',
        'Cor':                                                           'esmeralda',
        'Inseto':                                                        'eilema',
        'Nome feminino':                                                 'evalda',
        'Profissao':                                                     'escritor',
        'Ator':                                                          'emilio pitta',
        'Doce':                                                          'encharcada',
        'Idioma':                                                        'eslovaco',
        'Flor':                                                          'erva doce',
        'Palavra em ingles':                                             'end',
        'Jlr':                                                           'eleno',
        'Gentilico':                                                     'eleno',
        'Personagem ficticio':                                           'elizabeth barry',
        'Filme':                                                         'emoji',
        'Mse':                                                           'esbelta',
        'Desenho animado':                                               'emoji',
        'Fruta':                                                         'embauba',
        'Nome masculino':                                                'evaldo',
        'Capital':                                                       'estocolmo suecia',
        'Cantor':                                                        'eminem',
        'Esportista':                                                    'eden hazard',
        'Super heroi':                                                   'elektra',
        'Pda':                                                           'ende',
        'Objeto':                                                        'esfoliador',
        'Banda':                                                         'engenheiros do havai',
        'Meio de transporte':                                            'escavadeira'
    },
    'F': {
        'Carro':                                                         'fusca',
        'Sobremesa':                                                     'frape',
        'Sobrenome':                                                     'Ferreira',
        'Musica':                                                        'fatalidade',
        'Celebridade':                                                   'fausto silva',
        'Instrumento musical':                                           'flauta',
        'App ou site':                                                   'fut parodias',
        'Game':                                                          'fifa 10',
        'Eletro eletronico':                                             'fone de ouvido',
        'Verbo':                                                         'ficar',
        'Marca':                                                         'forever 21',
        'Cidade':                                                        'firenze',
        'Vestuario':                                                     'fralda',
        'Serie':                                                         'family guy',
        'Animal':                                                        'foca',
        'Time esportivo':                                                'firenze',
        'Cep':                                                           'firenze',
        'Remedio':                                                       'fenergan',
        'Pch':                                                           'falange',
        'Adjetivo':                                                      'folgado',
        'Programa de tv':                                                'fatima berndez',
        'Liquido':                                                       'fenergan',
        'Comida':                                                        'empada',
        'Esporte':                                                       'fisiculturismo',
        'Cor':                                                           'fucsia',
        'Inseto':                                                        'formiga',
        'Nome feminino':                                                 'fabiana',
        'Profissao':                                                     'filosofo',
        'Ator':                                                          'fabio assuncao',
        'Doce':                                                          'figada',
        'Idioma':                                                        'filipino',
        'Flor':                                                          'fenix',
        'Palavra em ingles':                                             'few',
        'Jlr':                                                           'fossa',
        'Gentilico':                                                     'fim',
        'Personagem ficticio':                                           'fada madrinha',
        'Filme':                                                         'furia mortal',
        'Mse':                                                           'fofoqueira',
        'Desenho animado':                                               'faisca e seus amigos',
        'Fruta':                                                         'figo',
        'Nome masculino':                                                'fabiano',
        'Capital':                                                       'freetown serra leoa',
        'Cantor':                                                        'frank sinastra',
        'Esportista':                                                    'fernandinho',
        'Super heroi':                                                   'flash',
        'Pda':                                                           'fola',
        'Objeto':                                                        'facao',
        'Banda':                                                         'foo fighters',
        'Meio de transporte':                                            'foguete'
    },
    'G': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'H': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'I': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'J': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'K': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'L': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'M': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'N': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'O': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'P': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'Q': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'R': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'S': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'T': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'U': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    },
    'V': {
        'Carro':                                                         '',
        'Sobremesa':                                                     '',
        'Sobrenome':                                                     '',
        'Musica':                                                        '',
        'Celebridade':                                                   '',
        'Instrumento musical':                                           '',
        'App ou site':                                                   '',
        'Game':                                                          '',
        'Eletro eletronico':                                             '',
        'Verbo':                                                         '',
        'Marca':                                                         '',
        'Cidade':                                                        '',
        'Vestuario':                                                     '',
        'Serie':                                                         '',
        'Animal':                                                        '',
        'Time esportivo':                                                '',
        'Cep':                                                           '',
        'Remedio':                                                       '',
        'Pch':                                                           '',
        'Adjetivo':                                                      '',
        'Programa de tv':                                                '',
        'Liquido':                                                       '',
        'Comida':                                                        '',
        'Esporte':                                                       '',
        'Cor':                                                           '',
        'Inseto':                                                        '',
        'Nome feminino':                                                 '',
        'Profissao':                                                     '',
        'Ator':                                                          '',
        'Doce':                                                          '',
        'Idioma':                                                        '',
        'Flor':                                                          '',
        'Palavra em ingles':                                             '',
        'Jlr':                                                           '',
        'Gentilico':                                                     '',
        'Personagem ficticio':                                           '',
        'Filme':                                                         '',
        'Mse':                                                           '',
        'Desenho animado':                                               '',
        'Fruta':                                                         '',
        'Nome masculino':                                                '',
        'Capital':                                                       '',
        'Cantor':                                                        '',
        'Esportista':                                                    '',
        'Super heroi':                                                   '',
        'Pda':                                                           '',
        'Objeto':                                                        '',
        'Banda':                                                         '',
        'Meio de transporte':                                            ''
    }
}

temas = [
   'Carro',
   'Sobremesa',
   'Sobrenome',
   'Música',
   'Celebridade',
   'Instrumento musical',
   'App ou site',
   'Game',
   'Eletro eletrônico',
   'Verbo',
   'Marca',
   'Cidade',
   'Vestuário',
   'Série',
   'Animal',
   'Time esportivo',
   'Cep',
   'Remédio',
   'Pch',
   'Adjetivo',
   'Programa de tv',
   'Líquido',
   'Comida',
   'Esporte',
   'Cor',
   'Inseto',
   'Nome feminino',
   'Profissao',
   'Ator',
   'Doce',
   'Idioma',
   'Flor',
   'Palavra em inglês',
   'Jlr',
   'Gentílico',
   'Personagem fictício',
   'Filme',
   'Msé',
   'Desenho animado',
   'Fruta',
   'Nome masculino',
   'Capital',
   'Cantor',
   'Esportista',
   'Super-herói',
   'Pda',
   'Objeto',
   'Banda',
   'Meio de transporte',
]